[build]
  # Comando de build para Next.js
  command = "npm run build"
  
  # Directorio de salida
  publish = "out"
  
  # Variables de entorno para el build
  environment = { NODE_VERSION = "18" }

[build.environment]
  # Variables de entorno para el build
  NODE_ENV = "production"
  NEXT_PUBLIC_API_URL = "https://tu-backend-url.com"
  NEXT_TELEMETRY_DISABLED = "1"

# Redirecciones para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https:;"

# Headers para archivos estáticos
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers para imágenes
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Configuración de funciones (si necesitas serverless functions)
[functions]
  directory = "netlify/functions"

# Configuración de plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configuración de formularios
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Configuración de deploy
[deploy]
  publish = "out"
